"""Two-tier LLM response caching system.

This module provides a caching layer for LLM responses with:
- In-memory LRU cache for fast access to hot data
- Disk-based JSON storage for persistence across restarts
- Thread-safe operations for concurrent access
- MD5-based cache keys from request parameters
"""

from __future__ import annotations

import hashlib
import json
import shutil
import threading
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, TYPE_CHECKING

from pydantic import BaseModel, Field, ValidationError

if TYPE_CHECKING:
    from src.llm.client import LLMResponse


class CacheEntry(BaseModel):
    """Cached LLM response with metadata.

    Attributes:
        content: The text content of the response.
        model: The model that generated the response.
        usage: Token usage statistics.
        stop_reason: Why the model stopped generating.
        raw_response: The complete raw response.
        created_at: When the entry was created.
        prompt_hash: The cache key for this entry.
        hit_count: Number of times this entry was accessed.
        last_accessed: When the entry was last accessed.
    """

    content: str
    model: str
    usage: Dict[str, int] = Field(default_factory=dict)
    stop_reason: Optional[str] = None
    raw_response: Optional[Dict[str, Any]] = None
    created_at: datetime
    prompt_hash: str
    hit_count: int = 0
    last_accessed: Optional[datetime] = None


class CacheStats(BaseModel):
    """Statistics about cache usage.

    Attributes:
        memory_hits: Number of cache hits from memory.
        disk_hits: Number of cache hits from disk.
        misses: Number of cache misses.
        memory_size: Current number of entries in memory cache.
        disk_entries: Current number of entries on disk.
    """

    memory_hits: int = 0
    disk_hits: int = 0
    misses: int = 0
    memory_size: int = 0
    disk_entries: int = 0


class LLMCache:
    """Two-tier LLM response cache (memory + disk).

    Provides fast access to cached LLM responses using:
    1. In-memory LRU cache for hot data
    2. Disk-based JSON storage for persistence

    Cache keys are generated by hashing the prompt and relevant parameters.

    Example:
        >>> cache = LLMCache(cache_dir=Path(".cache/llm_responses"))
        >>>
        >>> # Try to get cached response
        >>> cached = cache.get(prompt="Hello", model="claude-sonnet-4-20250514")
        >>> if cached:
        ...     return cached.content
        >>>
        >>> # Make API call and cache result
        >>> response = llm_client.complete(prompt)
        >>> cache.set(
        ...     prompt="Hello",
        ...     model="claude-sonnet-4-20250514",
        ...     response=response
        ... )
    """

    def __init__(
        self,
        cache_dir: Path = Path(".cache/llm_responses"),
        max_memory_entries: int = 1000,
        enabled: bool = True,
    ):
        """Initialize the cache.

        Args:
            cache_dir: Directory for disk cache storage.
            max_memory_entries: Maximum entries to keep in memory.
            enabled: Whether caching is enabled.
        """
        self._cache_dir = Path(cache_dir)
        self._max_memory_entries = max_memory_entries
        self._enabled = enabled

        # Thread safety
        self._lock = threading.RLock()

        # In-memory cache
        self._memory_cache: Dict[str, CacheEntry] = {}

        # Statistics
        self._stats = CacheStats()

        # Create cache directory if enabled
        if self._enabled:
            self._cache_dir.mkdir(parents=True, exist_ok=True)

    @property
    def enabled(self) -> bool:
        """Whether caching is enabled."""
        return self._enabled

    @enabled.setter
    def enabled(self, value: bool) -> None:
        """Enable or disable caching."""
        self._enabled = value
        if value and not self._cache_dir.exists():
            self._cache_dir.mkdir(parents=True, exist_ok=True)

    def get(
        self,
        prompt: str,
        *,
        model: str,
        system: Optional[str] = None,
        temperature: Optional[float] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        messages: Optional[List[Dict[str, Any]]] = None,
    ) -> Optional[CacheEntry]:
        """Retrieve cached response for a prompt.

        Checks memory cache first, then disk cache.
        If found on disk but not in memory, promotes to memory.

        Args:
            prompt: The user prompt (or empty string if using messages).
            model: Model name used for the request.
            system: Optional system prompt.
            temperature: Optional temperature setting.
            tools: Optional tools list (for tool-calling requests).
            messages: Optional message history (for chat requests).

        Returns:
            CacheEntry if found, None otherwise.
        """
        if not self._enabled:
            return None

        with self._lock:
            cache_key = self._compute_hash(
                prompt, model, system, temperature, tools, messages
            )

            # Check memory cache first
            if cache_key in self._memory_cache:
                entry = self._memory_cache[cache_key]
                entry.hit_count += 1
                entry.last_accessed = datetime.utcnow()
                self._stats.memory_hits += 1
                return entry

            # Check disk cache
            entry = self._load_from_disk(cache_key)
            if entry:
                # Promote to memory cache
                self._add_to_memory(cache_key, entry)
                self._stats.disk_hits += 1
                return entry

            self._stats.misses += 1
            return None

    def set(
        self,
        prompt: str,
        *,
        model: str,
        response: "LLMResponse",
        system: Optional[str] = None,
        temperature: Optional[float] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        messages: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """Store a response in the cache.

        Stores in both memory and disk cache.

        Args:
            prompt: The user prompt (or empty string if using messages).
            model: Model name used for the request.
            response: The LLM response to cache.
            system: Optional system prompt.
            temperature: Optional temperature setting.
            tools: Optional tools list.
            messages: Optional message history.

        Returns:
            The cache key (hash) for the stored entry.
        """
        if not self._enabled:
            # Still compute and return the key even if disabled
            return self._compute_hash(
                prompt, model, system, temperature, tools, messages
            )

        with self._lock:
            cache_key = self._compute_hash(
                prompt, model, system, temperature, tools, messages
            )

            # Create cache entry from response
            now = datetime.utcnow()
            entry = CacheEntry(
                content=response.content,
                model=response.model,
                usage=response.usage,
                stop_reason=response.stop_reason,
                raw_response=response.raw_response,
                created_at=now,
                prompt_hash=cache_key,
                hit_count=0,
                last_accessed=now,
            )

            # Store in memory
            self._add_to_memory(cache_key, entry)

            # Store on disk
            self._save_to_disk(cache_key, entry)

            return cache_key

    def _compute_hash(
        self,
        prompt: str,
        model: str,
        system: Optional[str] = None,
        temperature: Optional[float] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        messages: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """Compute MD5 hash for cache key.

        Creates a deterministic hash from all relevant request parameters.

        Args:
            prompt: User prompt.
            model: Model name.
            system: Optional system prompt.
            temperature: Optional temperature.
            tools: Optional tools list.
            messages: Optional message history.

        Returns:
            32-character hexadecimal MD5 hash string.
        """
        # Build a dict with all relevant parameters
        hash_input: Dict[str, Any] = {
            "prompt": prompt,
            "model": model,
        }

        # Only include optional params if set (for deterministic hashing)
        if system is not None:
            hash_input["system"] = system
        if temperature is not None:
            hash_input["temperature"] = temperature
        if tools is not None:
            # Convert to JSON string for consistent hashing
            hash_input["tools"] = json.dumps(tools, sort_keys=True)
        if messages is not None:
            hash_input["messages"] = json.dumps(messages, sort_keys=True)

        # Create deterministic JSON string and hash it
        hash_str = json.dumps(hash_input, sort_keys=True)
        return hashlib.md5(hash_str.encode()).hexdigest()

    def _get_disk_path(self, cache_key: str) -> Path:
        """Get the disk path for a cache key.

        Uses a two-level directory structure to avoid too many files
        in a single directory: cache_dir/ab/abcdef123456.json

        Args:
            cache_key: The cache key (hash).

        Returns:
            Path to the cache file.
        """
        # Use first 2 characters as subdirectory
        subdir = cache_key[:2]
        return self._cache_dir / subdir / f"{cache_key}.json"

    def _load_from_disk(self, cache_key: str) -> Optional[CacheEntry]:
        """Load a cache entry from disk.

        Args:
            cache_key: The cache key to load.

        Returns:
            CacheEntry if found and valid, None otherwise.
        """
        file_path = self._get_disk_path(cache_key)

        if not file_path.exists():
            return None

        try:
            with open(file_path, "r") as f:
                data = json.load(f)
            return CacheEntry.model_validate(data)
        except (json.JSONDecodeError, ValidationError, OSError):
            # Corrupted or invalid cache file - delete it
            try:
                file_path.unlink(missing_ok=True)
            except OSError:
                pass
            return None

    def _save_to_disk(self, cache_key: str, entry: CacheEntry) -> None:
        """Save a cache entry to disk.

        Args:
            cache_key: The cache key.
            entry: The cache entry to save.
        """
        file_path = self._get_disk_path(cache_key)
        file_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            with open(file_path, "w") as f:
                json.dump(entry.model_dump(mode="json"), f, indent=2, default=str)
        except OSError:
            # Silently fail on disk write errors
            pass

    def _add_to_memory(self, cache_key: str, entry: CacheEntry) -> None:
        """Add entry to memory cache with LRU eviction.

        Args:
            cache_key: The cache key.
            entry: The cache entry to add.
        """
        # Evict if at capacity
        if len(self._memory_cache) >= self._max_memory_entries:
            # Find least recently accessed entry
            if self._memory_cache:
                oldest_key = min(
                    self._memory_cache.keys(),
                    key=lambda k: self._memory_cache[k].last_accessed
                    or datetime.min,
                )
                del self._memory_cache[oldest_key]

        entry.last_accessed = datetime.utcnow()
        self._memory_cache[cache_key] = entry

    def invalidate(self, cache_key: str) -> bool:
        """Remove a specific entry from both caches.

        Args:
            cache_key: The cache key to invalidate.

        Returns:
            True if entry was found and removed, False otherwise.
        """
        with self._lock:
            found = False

            # Remove from memory
            if cache_key in self._memory_cache:
                del self._memory_cache[cache_key]
                found = True

            # Remove from disk
            file_path = self._get_disk_path(cache_key)
            if file_path.exists():
                try:
                    file_path.unlink()
                    found = True
                except OSError:
                    pass

            return found

    def clear(self) -> None:
        """Clear all cache entries (memory and disk)."""
        with self._lock:
            # Clear memory cache
            self._memory_cache.clear()

            # Clear disk cache
            if self._cache_dir.exists():
                try:
                    shutil.rmtree(self._cache_dir)
                    self._cache_dir.mkdir(parents=True, exist_ok=True)
                except OSError:
                    pass

            # Reset stats
            self._stats = CacheStats()

    def get_stats(self) -> CacheStats:
        """Get cache statistics.

        Returns:
            CacheStats with hit/miss counts and sizes.
        """
        with self._lock:
            # Update current sizes
            self._stats.memory_size = len(self._memory_cache)

            # Count disk entries
            disk_count = 0
            if self._cache_dir.exists():
                try:
                    for subdir in self._cache_dir.iterdir():
                        if subdir.is_dir():
                            disk_count += sum(
                                1 for f in subdir.iterdir() if f.suffix == ".json"
                            )
                except OSError:
                    pass
            self._stats.disk_entries = disk_count

            return self._stats.model_copy()


def create_cache_from_config(config: Any) -> LLMCache:
    """Create LLMCache from application config.

    Args:
        config: Application Config instance (from src.config.Config).

    Returns:
        Configured LLMCache instance.

    Example:
        >>> from src.config import load_config
        >>> config = load_config()
        >>> cache = create_cache_from_config(config)
    """
    return LLMCache(
        cache_dir=config.cache.directory / "llm_responses",
        enabled=config.cache.enabled,
    )
